### ISSUE TITLE
Invalid zip code

### ISSUE THREAD

**Issue by Pohli** [xXSparkeyy/harbour-spritradar#16]
I often get the error message "Invalid zip code" after typing a German 5digit zip code into the search field and then after two or more tries it suddenly works and presents me results.
Besides that it's a very useful app, thank you!

**Comment by xXSparkeyy** [comment]
Thanks! I can't reproduce the bug right now, but I will take a look at it when i finished my exams.

**Comment by Armadill0** [comment]
I can confirm that issue. It happens quite frequently, but not always. Had no time for further debugging. Maybe I can have a look into this the next days.

The error itself is being displayed instant, so a timeout can be excluded.

**Comment by Pohli** [comment]
I forgot to mention that sometimes, after I got the error message and returned back to the search field, the app has replaced my entered zip code with an American address containing 5 digits codes, too. But this doesn't happen every time when I get the Invalid zip code message, only in some cases.

**Comment by hoehnp** [comment]
I can confirm that the issue still exists. I suspect the problem is that from my knowledge the google service to determine the geo coordinates has been shut down. I submitted a PR which resolves this. However, the variable address still needs to be split into a variable for the street and a variable for the city.

**Comment by clausmichele** [comment]
With the italian database is telling me "Invalid zip code"
